Fixed exit code.

diff --git a/ceibal-update b/ceibal-update
--- a/ceibal-update
+++ b/ceibal-update
@@ -4,12 +4,14 @@ logger "Actualizando Ceibal."
 
 apt-get update -y
 if [ $? -ne 0 ]; then
-    exit $?
+    logger "Error ejecutando apt-get update ($?)."
+    exit 1
 fi
 
 apt-get install -y -o Dpkg::Options::="--force-confnew" ceibal-update
 if [ $? -ne 0 ]; then
-    exit $?
+    logger "Error ejecutando apt-get install ($?)."
+    exit 2
 fi
 
 apt-get autoremove
